name: Setup Ant
description: Set up your GitHub Actions workflow with a specific version of Apache Ant.
author: Cédric Belin

branding:
  color: red
  icon: download

inputs:
  version:
    description: The version number of the Apache Ant package.
    default: 1.10.13
    required: false

runs:
  using: node16
  main: bin/setup_ant.js
